[build]
  command = "pip install -r requirements.txt && python summary.py"
  functions = "lambda"

[dev]
  command = "flask run"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

